UPDATE `leases` SET `room_id` = 1 WHERE `room_id` = 101;
UPDATE `leases` SET `room_id` = 2 WHERE `room_id` = 102;
UPDATE `leases` SET `room_id` = 3 WHERE `room_id` = 103;
UPDATE `leases` SET `room_id` = 4 WHERE `room_id` = 104;
UPDATE `leases` SET `room_id` = 5 WHERE `room_id` = 105;
UPDATE `leases` SET `room_id` = 6 WHERE `room_id` = 106;
UPDATE `leases` SET `room_id` = 7 WHERE `room_id` = 107;
UPDATE `leases` SET `room_id` = 8 WHERE `room_id` = 108;
UPDATE `leases` SET `room_id` = 9 WHERE `room_id` = 109;

UPDATE `leases` SET `room_id` = 1 WHERE `room_id` = 201;
UPDATE `leases` SET `room_id` = 2 WHERE `room_id` = 202;
UPDATE `leases` SET `room_id` = 3 WHERE `room_id` = 203;
UPDATE `leases` SET `room_id` = 4 WHERE `room_id` = 204;
UPDATE `leases` SET `room_id` = 5 WHERE `room_id` = 205;
UPDATE `leases` SET `room_id` = 6 WHERE `room_id` = 206;
UPDATE `leases` SET `room_id` = 7 WHERE `room_id` = 207;
UPDATE `leases` SET `room_id` = 8 WHERE `room_id` = 208;
UPDATE `leases` SET `room_id` = 9 WHERE `room_id` = 209;

UPDATE `leases` SET `room_id` = 1 WHERE `room_id` = 301;
UPDATE `leases` SET `room_id` = 2 WHERE `room_id` = 302;
UPDATE `leases` SET `room_id` = 3 WHERE `room_id` = 303;
UPDATE `leases` SET `room_id` = 4 WHERE `room_id` = 304;
UPDATE `leases` SET `room_id` = 5 WHERE `room_id` = 305;
UPDATE `leases` SET `room_id` = 6 WHERE `room_id` = 306;
UPDATE `leases` SET `room_id` = 7 WHERE `room_id` = 307;
UPDATE `leases` SET `room_id` = 8 WHERE `room_id` = 308;
UPDATE `leases` SET `room_id` = 9 WHERE `room_id` = 309;